theme: jekyll-theme-minimal

name: Willem Gispen
title: Willem Gispen
description: Graduate student specializing in theoretical condensed matter physics.
email: willemgispen@outlook.com

logo: willem.jpg
icon: willem.jpg
